---
- name: Create tarsnap script
  template:
    src: templates/tarsnap.sh.j2
    dest: ~/bin/tarsnap.sh
    mode: 0700
  when: configure_tarsnap == "yes"

- name: Create tarsnap systemd timer file
  copy:
    src: files/tarsnap.timer
    dest: ~/.config/systemd/user/tarsnap.timer
  when: configure_tarsnap == "yes"

- name: Create tarsnap systemd service file
  copy:
    src: files/tarsnap.service
    dest: ~/.config/systemd/user/tarsnap.service
  when: configure_tarsnap == "yes"

- name: Enable tarsnap systemd timer
  systemd:
    name: tarsnap.timer
    state: started
    enabled: yes
    user: yes
  when: configure_tarsnap == "yes"

