#!/bin/sh

USER_NAME=$(w -hs | awk -v vt=tty$(fgconsole) '$0 ~ vt {print $1}')
export DISPLAY=:0
export XAUTHORITY=/home/$USER_NAME/.Xauthority

IN="eDP1"
EXT="HDMI1"

if (xrandr | grep "$EXT disconnected"); then
    	xrandr --output $EXT --off --output $IN --auto
else
	xrandr --output $IN --auto --output $EXT --auto --panning 3840x2160+3840+0 --scale 2x2 --right-of eDP1 
fi
