---
# Here we describe every software we may want to install
- hosts: all
  tasks:
    - name: Install apt-transport-https
      apt: name=apt-transport-https state=present
      become: yes

    # Edify Debian repo
    - name: Install Edify repo key
      apt_key: url='https://{{artifactory_username}}:{{artifactory_password}}@edify.jfrog.io/edify/api/gpg/key/public' state=present
      become: yes

    - name: Install Edify repo
      apt_repository: repo='deb https://{{artifactory_username}}:{{artifactory_password}}@edify.jfrog.io/edify/debian-local stable main'
      become: yes

    # Skype
    - name: Install Skype repo key
      apt_key: url='https://repo.skype.com/data/SKYPE-GPG-KEY' state=present
      become: yes

    - name: Install Skype repo
      apt_repository: repo='deb [arch=amd64] https://repo.skype.com/deb stable main' filename='skype-stable' state=present
      become: yes

    # NodeJS
    - name: Install NodeJS repo key
      apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key state=present
      become: yes

    - name: Install NodeJS repo
      apt_repository: repo='deb https://deb.nodesource.com/node_6.x {{ansible_distribution_release}} main' state=present
      become: yes

    # Heroku Toolbelt
    - name: Install Heroku Toolbelt repo key
      apt_key: url=https://toolbelt.heroku.com/apt/release.key state=present
      become: yes

    - name: Install Heroku Toolbelt repo
      apt_repository: repo='deb http://toolbelt.heroku.com/ubuntu ./' state=present
      become: yes

    # Infinality
    - name: Install OpenJDK infinality repo
      apt_repository: repo='ppa:no1wantdthisname/openjdk-fontfix' state=present
      become: yes

    - name: Installinfinality repo
      apt_repository: repo='ppa:no1wantdthisname/ppa' state=present
      become: yes

    # Ubuntu Make
    - name: Install Ubuntu Make repo
      apt_repository: repo='ppa:ubuntu-desktop/ubuntu-make'
      become: yes

    # Gradle
    - name: Install Gradle PPA repo
      apt_repository: repo='ppa:cwchien/gradle'
      become: yes

    # Atom
    - name: Install Atom PPA repo
      apt_repository: repo='ppa:webupd8team/atom'
      become: yes

    # Google Chrome
    - name: Install Google Chrome repo key
      apt_key: url='https://dl-ssl.google.com/linux/linux_signing_key.pub' state=present
      become: yes

    - name: Install Google Chrome repo
      apt_repository: repo='deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' filename='google-chrome' state=present
      become: yes

    - name: Install Google Cloud SDK repo key
      apt_key: url='https://packages.cloud.google.com/apt/doc/apt-key.gpg' state=present
      become: yes

    - name: Install Google Cloud SDK repo
      apt_repository: repo='deb https://packages.cloud.google.com/apt cloud-sdk-{{ansible_distribution_release}} main' state=present
      become: yes

    # Base packages Ubuntu only
    - name: Install base system packages
      apt: name={{ item }} state=latest
      become: yes
      with_items:
        - xautolock
        - git-flow
        - rofi
        - unity-tweak-tool
        - arc-theme
        - openjdk-8-jdk
        - nodejs
        - heroku-toolbelt
        - golang
        - docker-engine
        - ubuntu-make
        - ruby2.3
        - ruby2.3-dev
        - gradle
        - skypeforlinux
        - vagrant
        - google-chrome-stable
        - openssh-server
        - vim-nox
        - build-essential
        - subversion
        - bzr
        - tmux
        - cloc
        - zsh
        - git
        - git-flow
        - python
        - python-dev
        - python-setuptools
        - libpq-dev
        - mercurial
        - curl
        - openvpn
        - keychain
        - p7zip-full
        - xz-utils
        - python-pip
        - qemu-kvm
        - libvirt-bin
        - virt-manager
        - libxslt-dev
        - libxml2-dev
        - libvirt-dev
        - zlib1g-dev
        - fonts-hack-ttf
        - apt-transport-https
        - atom
        - i3
        - i3blocks
        - slack-desktop
        - rsync
        - direnv
        - prey
        - code
        - nylas
        - google-cloud-sdk
        - xfce4-terminal
        - lxappearance
        - lm-sensors
        - fonts-font-awesome
        - feh
        - jq
        - pavucontrol
        - htop

    - name: Remove old versions base packages
      apt: name={{ item }} state=absent purge=yes autoremove=yes
      become: yes
      with_items:
        - openjdk-7-jre-headless
        - openjdk-7-jre
        - gnome-games-common
        - example-content
        - firefox
        - xul-ext-ubufox
        - rhythmbox
        - thunderbird-gnome-support
        - thunderbird
        - totem
        - transmission-gtk

