---
- hosts: all
  vars:
    dotfiles_repo: https://github.com/jarias/dotfiles.git
  roles:
    - i3
    - base
    - golang
    - node
    - ruby
    - python
    - vagrant
    - vim
    - jetbrains
    - gotools
    - ohmyzsh
    - dotfiles
    - backups
    - base16
    - user

