---
- hosts: all
  roles:
    - apt
    - slack
    - visual-studio-code
    - prey
    - zsh
    - openssh-server
    - dev-tools
    - fonts
    - libvirt
    - openvpn
    - git
    - java
    - keybase
    - i3
    - neovim
    - golang
    - node
    - ruby
    - python
    - vagrant
    - vim
    - jetbrains
    - ohmyzsh
    - dotfiles
    - backups
    - base16
    - user
    - wine
    - obs
    - polybar
    - firefox
    - yarn
    - chrome
    - docker
    - gradle
    - heroku
    - r
    - skype
    - tmate
    - yubico
    - google-cloud-sdk
    - atom
    - enpass

