# Copyright 2015 Julio Arias
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
# Here we describe every software we may want to install
- hosts: all
  tasks:
    - name: "add infinality-bundle key"
      shell: "pacman-key -r 962DDE58 && pacman-key --lsign-key 962DDE58"
      changed_when: false
      become: yes
      become_method: sudo

    - name: "add menari.org repo"
      lineinfile:
        dest: "/etc/pacman.conf"
        state: "present"
        line: "{{ item }}"
      with_items:
        - "[menari]"
        - "Server = http://repo.menari.org/$arch"
        - "SigLevel = Never"
      become: yes
      become_method: sudo

    - name: "enable multilib"
      lineinfile:
        dest: "/etc/pacman.conf"
        state: "present"
        line: "{{ item }}"
      with_items:
        - "[multilib]"
        - "Include = /etc/pacman.d/mirrorlist"
      become: yes
      become_method: sudo

    - pacman: update_cache=yes
      become: yes
      become_method: sudo

    # Base packages
    - name: Install base system packages
      pacman: name={{ item }} state=latest
      become: yes
      become_method: sudo
      with_items:
        - bzr
        - jdk8-openjdk-infinality
        - tmux
        - cloc
        - ctags
        - zsh
        - git
        - mercurial
        - curl
        - ruby
        - gvim
        - unzip
        - openvpn
        - openssh
        - graphviz
        - keychain
        - nodejs
        - npm
        - xorg-xrdb
        - i3-wm
        - i3lock
        - rofi
        - p7zip
        - xz
        - lxappearance
        - imagemagick
        - docker
        - go
        - vagrant
        - pulseaudio
        - pulseaudio-alsa
        - python-setuptools
        - python2
        - python
        - pavucontrol
        - postgresql-libs
        - infinality-bundle
        - lm_sensors
        - xautolock
        - tree
        - scummvm
        - scummvm-tools
        - samba
        - rsync
        - ranger
        - xfce4-power-manager
        - xfce4-terminal
        - maven
        - gradle
        - weechat
        - noto-fonts
        - noto-fonts-emoji
        - mpv
        - go-tools
        - tomcat7
        - adobe-source-code-pro-fonts
        - powerline-fonts
        - xawtv
        - scrot
        - mpg123
        - autofs
        - libvirt
        - virt-manager
        - qemu
        - perf
        - terminus-font
        - vinagre
        - dnsmasq
        - intel-ucode
        - ngrok
        - google-cloud-sdk
        - arduino
        - atom-editor-bin
        - cairo-infinality
        - cfssl
        - direnv
        - debtap
        - dropbox
        - epson-inkjet-printer-escpr
        - flamegraph-git
        - fontconfig-infinality
        - freetype2-infinality
        - google-chrome
        - i3blocks
        - heroku-toolbelt
        - intellij-idea-ultimate-edition
        - j4-dmenu-desktop
        - jdk8-openjdk-infinality
        - keybase-bin
        - ltunify-git
        - moka-icon-theme-git
        - n1
        - openvpn-update-resolv-conf
        - otf-fira-code
        - prey-node-client
        - skypeforlinux-bin
        - slack-desktop
        - ttf-font-awesome
        - visual-studio-code
        - xreader
        - xviewer
        - wine-gaming-nine

    - name: Install Python pip
      easy_install: name=pip
      become: yes
      become_method: sudo

    # Gems
    - name: Install default Ruby Gems
      gem: name={{ item }} state=present user_install=yes
      with_items:
        - bundler
        - homesick
        - git-smart
        - berkshelf
        - ghost
        - lolcat

    # NPM
    - name: Setup NPM prefix
      command: /usr/bin/npm config set prefix '~/.npm-packages'
               creates=~/.npmrc
    - name: Install NPM default packages
      npm: name={{ item }} global=yes
      with_items:
        - grunt-cli
        - bower
        - yo
        - sslmate
        - standard
        - eslint
        - ember-cli
        - gulp-cli

    # Python pip
    - name: Install Python pip default packages
      pip: name={{ item }} extra_args='--user'
      with_items:
        - awscli
        - psutil
        - docker-compose
        - pgcli
        - mycli
        - http-prompt

    - name: Create GOPATH dir
      file: state=directory path="~/Golang"
    - name: Install default Go packages
      shell: GOPATH=~/Golang go get {{ item.package }}
      with_items:
        - { package: golang.org/x/tools/cmd/gotype }
        - { package: golang.org/x/tools/cmd/goimports }
        - { package: golang.org/x/tools/cmd/cover }
        - { package: golang.org/x/tools/cmd/guru }
        - { package: golang.org/x/tools/cmd/gorename }
        - { package: github.com/nsf/gocode }
        - { package: github.com/alecthomas/gometalinter }
        - { package: github.com/golang/lint/golint }
        - { package: github.com/rogpeppe/godef }
        - { package: github.com/kisielk/errcheck }
        - { package: github.com/jstemmer/gotags }
        - { package: github.com/klauspost/asmfmt/cmd/asmfmt }
        - { package: github.com/fatih/motion }
        - { package: github.com/zmb3/gogetdoc }
        - { package: github.com/josharian/impl }
        - { package: github.com/constabulary/gb/... }

    # Vagrant plugins
    - name: Install Vagrant plugins
      command: vagrant plugin install {{ item }}
      with_items:
        - vagrant-vbguest
        - vagrant-mutate
        - vagrant-libvirt

    # Vim plugins
    - name: Create bundle directory
      file: path=~/.vim/bundle state=directory recurse=true

    - name: Create autoload directory
      file: path=~/.vim/autoload state=directory recurse=true

    - name: Install Pathogen
      get_url: url=https://raw.github.com/tpope/vim-pathogen/master/autoload/pathogen.vim
               dest=~/.vim/autoload/pathogen.vim

    - name: Install Vim plugins
      git: repo={{ item.repo }} dest=~/.vim/bundle/{{ item.name }}
      with_items:
        - { repo: 'https://github.com/Shougo/neocomplete.vim', name: 'neocomplete.tool' }
        - { repo: 'https://github.com/scrooloose/nerdtree.git', name: 'nerdtree.tool' }
        - { repo: 'https://github.com/jeetsukumaran/vim-buffergator.git', name: 'buffergator.tool' }
        - { repo: 'https://github.com/tpope/vim-fugitive.git', name: 'fugitive.tool' }
        - { repo: 'https://github.com/fatih/vim-go.git', name: 'go.lang' }
        - { repo: 'https://github.com/pangloss/vim-javascript.git', name: 'javascript.lang' }
        - { repo: 'https://github.com/kien/ctrlp.vim.git', name: 'ctrlp.tool' }
        - { repo: 'https://github.com/Lokaltog/vim-easymotion.git', name: 'easymotion.tool' }
        - { repo: 'https://github.com/tpope/vim-git.git', name: 'git.lang' }
        - { repo: 'https://github.com/bronson/vim-trailing-whitespace.git', name: 'trailing-whitespace.tool' }
        - { repo: 'https://github.com/terryma/vim-multiple-cursors.git', name: 'multiple-cursors.tool' }
        - { repo: 'https://github.com/scrooloose/syntastic.git', name: 'syntastic.tool' }
        - { repo: 'https://github.com/tpope/vim-sensible.git', name: 'vim-sensible.config' }
        - { repo: 'https://github.com/majutsushi/tagbar.git', name: 'tagbar.tool' }
        - { repo: 'https://github.com/vim-scripts/ZoomWin.git', name: 'ZoomWin.tool' }
        - { repo: 'https://github.com/chriskempson/base16-vim.git', name: 'base16.color' }
        - { repo: 'https://github.com/SirVer/ultisnips.git', name: 'utilsnips.tool' }
