# Copyright 2015 Julio Arias
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
# Here we describe every software we may want to install
- hosts: all
  tasks:
    - name: "add archlinuxfr repository to pacman"
      lineinfile:
        dest: "/etc/pacman.conf"
        state: "present"
        line: "{{ item }}"
      with_items:
        - "[archlinuxfr]"
        - "SigLevel = Never"
        - "Server = http://repo.archlinux.fr/$arch"
      become: yes
      become_method: sudo

    - name: "add infinality-bundle key"
      shell: "pacman-key -r 962DDE58 && pacman-key --lsign-key 962DDE58"
      changed_when: false
      become: yes
      become_method: sudo

    - name: "add infinality-bundle" # https://wiki.archlinux.org/index.php/Unofficial_user_repositories#infinality-bundle
      lineinfile:
        dest: "/etc/pacman.conf"
        state: "present"
        line: "{{ item }}"
      with_items:
        - "[infinality-bundle]"
        - "Server = http://bohoomil.com/repo/$arch"
        - "Server = http://bohoomil.com/repo/fonts"
      become: yes
      become_method: sudo

    - name: "enable multilib"
      lineinfile:
        dest: "/etc/pacman.conf"
        state: "present"
        line: "{{ item }}"
      with_items:
        - "[multilib]"
        - "Include = /etc/pacman.d/mirrorlist"
      become: yes
      become_method: sudo

    - pacman: update_cache=yes
      become: yes
      become_method: sudo

    # Base packages
    - name: Install base system packages
      pacman: name={{ item }} state=latest
      become: yes
      become_method: sudo
      with_items:        
        - bzr
        - jdk8-openjdk-infinality
        - tmux
        - cloc
        - ctags
        - zsh
        - git
        - mercurial    
        - curl
        - ruby
        - gvim
        - unzip
        - openvpn
        - openssh
        - graphviz
        - keychain
        - nodejs
        - npm
        - xorg-xrdb
        - i3-wm
        - i3lock
        - rofi
        - p7zip
        - xz
        - lxappearance
        - imagemagick
        - docker
        - go
        - yaourt
        - vagrant
        - pulseaudio
        - pulseaudio-alsa
        - python-setuptools
        - python2
        - python
        - pavucontrol
        - postgresql-libs
        - infinality-bundle
        - lm_sensors        
        - xautolock
        - tree
        - scummvm
        - scummvm-tools
        - samba
        - rsync
        - ranger
        - xfce4-power-manager
        - xfce4-terminal
        - maven
        - gradle
        - weechat
        - noto-fonts
        - noto-fonts-emoji
        - mpv
        - go-tools
        - tomcat7
        - adobe-source-code-pro-fonts
        - powerline-fonts

    - name: Install Python pip
      easy_install: name=pip
      become: yes
      become_method: sudo

    # Gems
    - name: Install default Ruby Gems
      gem: name={{ item }} state=present user_install=yes
      with_items:
        - bundler
        - homesick
        - git-smart
        - berkshelf
        - ghost
        - lolcat

    # NPM
    - name: Setup NPM prefix
      command: /usr/bin/npm config set prefix '~/.npm-packages'
               creates=~/.npmrc
    - name: Install NPM default packages
      npm: name={{ item }} global=yes
      with_items:
        - grunt-cli
        - bower
        - yo
        - sslmate
        - standard

    # Python pip
    - name: Install Python pip default packages
      pip: name={{ item }} extra_args='--user'
      with_items:
        - awscli
        - psutil
        - docker-compose
        - pgcli
        - mycli
        - http-prompt

    - name: Create GOPATH dir
      file: state=directory path="~/Golang"
    - name: Install default Go packages
      shell: GOPATH=~/Golang go get {{ item.package }}
      with_items:
        - { package: github.com/tools/godep }
        - { package: golang.org/x/tools/cmd/gotype }
        - { package: golang.org/x/tools/cmd/goimports }
        - { package: golang.org/x/tools/cmd/cover }
        - { package: github.com/constabulary/gb/... }

    # Heroku plugins
    - name: Install Heroku plugins
      command: heroku plugins:install {{ item }}
      with_items:
        - https://github.com/ddollar/heroku-accounts.git
        - https://github.com/heroku/heroku-pg-extras.git
        - https://github.com/ddollar/heroku-pg-transfer.git

    # Vagrant plugins
    - name: Install Vagrant plugins
      command: vagrant plugin install {{ item }}
      with_items:
        - vagrant-vbguest

    # Vim plugins
    - name: Create bundle directory
      file: path=~/.vim/bundle state=directory recurse=true

    - name: Create autoload directory
      file: path=~/.vim/autoload state=directory recurse=true

    - name: Install Pathogen
      get_url: url=https://raw.github.com/tpope/vim-pathogen/master/autoload/pathogen.vim
               dest=~/.vim/autoload/pathogen.vim

    - name: Install Vim plugins
      git: repo={{ item.repo }} dest=~/.vim/bundle/{{ item.name }}
      with_items:
        - { repo: 'https://github.com/lilydjwg/colorizer', name: 'colorizer.tool' }
        - { repo: 'https://github.com/Shougo/neocomplete.vim', name: 'neocomplete.tool' }
        - { repo: 'https://github.com/mileszs/ack.vim.git', name: 'ack.tool' }
        - { repo: 'https://github.com/vim-scripts/molokai.git', name: 'molokai.color' }
        - { repo: 'https://github.com/scrooloose/nerdtree.git', name: 'nerdtree.tool' }
        - { repo: 'https://github.com/jeetsukumaran/vim-buffergator.git', name: 'buffergator.tool' }
        - { repo: 'https://github.com/tpope/vim-fugitive.git', name: 'fugitive.tool' }
        - { repo: 'https://github.com/fatih/vim-go.git', name: 'go.lang' }
        - { repo: 'https://github.com/pangloss/vim-javascript.git', name: 'javascript.lang' }
        - { repo: 'https://github.com/mmalecki/vim-node.js.git', name: 'nodejs.lang' }
        - { repo: 'https://github.com/kien/ctrlp.vim.git', name: 'ctrlp.tool' }
        - { repo: 'https://github.com/scrooloose/nerdcommenter.git', name: 'nerdcommenter.tool' }
        - { repo: 'https://github.com/ervandew/supertab.git', name: 'supertab.tool' }
        - { repo: 'https://github.com/Lokaltog/vim-easymotion.git', name: 'easymotion.tool' }
        - { repo: 'https://github.com/tpope/vim-git.git', name: 'git.lang' }
        - { repo: 'https://github.com/tfnico/vim-gradle.git', name: 'gradle.lang' }
        - { repo: 'https://github.com/groenewege/vim-less.git', name: 'less.lang' }
        - { repo: 'https://github.com/bronson/vim-trailing-whitespace.git', name: 'trailing-whitespace.tool' }
        - { repo: 'https://github.com/terryma/vim-multiple-cursors.git', name: 'multiple-cursors.tool' }
        - { repo: 'https://github.com/scrooloose/syntastic.git', name: 'syntastic.tool' }
        - { repo: 'https://github.com/maksimr/vim-jsbeautify.git', name: 'jsbeautify.tool' }
        - { repo: 'https://github.com/tpope/vim-sensible.git', name: 'vim-sensible.config' }
        - { repo: 'https://github.com/majutsushi/tagbar.git', name: 'tagbar.tool' }
        - { repo: 'https://github.com/vim-scripts/ZoomWin.git', name: 'ZoomWin.tool' }
