---
- name: Modify current user groups and shell
  user: name={{ lookup('env','USER') }} groups=libvirt append=yes shell=/usr/bin/zsh
  become: yes

- name: Create user systemd folder
  file: path=~/.config/systemd/user/ state=directory recurse=yes

