---
- name: Install video tools
  pacman:
    name: "{{ item }}"
  with_items:
    - mpv
    - mkvtoolnix-gui
    - handbrake
    - ffmpeg
  become: yes

- name: Install aur video packages
  command: packer --noedit --noconfirm -S makemkv
