---
- name: Clone homesick repos
  shell: '$(ruby -e "print Gem.user_dir")/bin/homesick clone {{item.repo}}'
    creates: ~/.homesick/repos/{{ item.name }}
  with_items:
    - { repo: "{{ dotfiles_repo }}", name: dotfiles }

- name: Symlink dotfiles
  shell: '$(ruby -e "print Gem.user_dir")/bin/homesick symlink --force dotfiles'
