---
- include_tasks: ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- include_tasks: arch.yml
  when: ansible_distribution == "Archlinux"

- name: Update pip
  pip:
    name: "pip"
    extra_args: "--upgrade"
    executable: pip3
  become: yes

- name: Install Python pip default packages
  pip:
    name: "{{ item }}"
    extra_args: "--user -U"
    executable: pip3
  with_items:
    - awscli
    - pgcli
    - http-prompt
    - saws
    - autopep8
    - buku

