---
- name: Install python
  apt:
    name: "{{ item }}"
  become: yes
  with_items:
    - python
    - python-dev
    - python-setuptools
    - python-pip

- name: Install pip packages dependencies
  apt:
    name: "{{ item }}"
  become: yes
  with_items:
    - libpq-dev
    - libssl-dev
