---
- name: Install termite dependencies
  apt:
    name: "{{ item }}"
  become: yes
  with_items:
    - g++
    - libgtk-3-dev
    - gtk-doc-tools
    - gnutls-bin
    - valac
    - intltool
    - libpcre2-dev
    - libglib3.0-cil-dev
    - libgnutls28-dev
    - libgirepository1.0-dev
    - libxml2-utils
    - gperf

- name: Clone vte-ng repo
  git:
    repo: https://github.com/thestinger/vte-ng.git
    dest: /usr/local/src/vte-ng
    update: yes
  become: yes

- name: Install vte-ng
  shell: "./autogen.sh && make && make install"
  args:
    chdir: /usr/local/src/vte-ng
  become: yes

- name: Clone termite repo
  git:
    repo: https://github.com/thestinger/termite.git
    dest: /usr/local/src/termite
    update: yes
    recursive: yes
  become: yes

- name: Install termite
  shell: "make && make install"
  args:
    chdir: /usr/local/src/termite
  become: yes

- name: Link term info
  file:
    src: /usr/local/share/terminfo/x/xterm-termite
    dest: /lib/terminfo/x/xterm-termite
    state: link
  become: yes
