---
- name: Install i3ipc-glib for polybar
  command: packer --noedit --noconfirm -S i3ipc-glib-git

- name: Install i3 and extras
  pacman:
    name: "{{ item }}"
  become: yes
  with_items:
    - i3-wm
    - i3lock
    - xautolock
    - feh
    - pavucontrol
    - lxappearance-gtk3
    - vinagre
    - rofi
    - arc-gtk-theme
    - xfce4-screenshooter
    - xfce4-power-manager
    - udiskie
    - scrot
    - qutebrowser
    - pulseaudio
    - pulseaudio-alsa
    - alsa-tools
    - dunst

- name: enable pulsaudio socket
  systemd:
    name: pulseaudio.socket
    enabled: yes
    state: started
    user: yes
