---
- name: Install i3
  apt:
    name: i3
  become: yes

- name: Install desktop enviroment extras
  apt:
    name: "{{ item }}"
  become: yes
  with_items:
    - xautolock
    - feh
    - pavucontrol
    - lxappearance
    - vinagre
    - rofi
    - arc-theme

