---
- name: Register the current Terraform version (if any)
  shell: /usr/local/bin/terraform version | cut -d ' ' -f2 | sed 's/v\(.*\)/\1/' | tr -d '\n'
  ignore_errors: yes
  register: terraform_version

- name: Install Terraform
  unarchive:
    src: "https://releases.hashicorp.com/terraform/{{ terraform_version_target }}/terraform_{{ terraform_version_target }}_linux_amd64.zip"
    dest: /usr/local/bin
    remote_src: True
  become: yes
  when: terraform_version|failed or terraform_version.stdout != terraform_version_target
