---
- name: Install mpd
  pacman:
    name: "{{ item }}"
  become: yes
  with_items:
    - mpd
    - mpc

- name: Install ncmcpp
  pacman:
    name: ncmcpp
  become: yes

- name: Enable mpd service
  systemd:
    name: mpd
    enabled: yes
    state: started
    user: yes
