---
- name: Install mpd
  pacman:
    name: mpd
  become: yes

- name: Install ncmcpp
  pacman:
    name: ncmcpp
  become: yes

- name: Enable mpd service
  systemd:
    name: mpd
    enabled: yes
    state: started
    user: yes
