---
- include_tasks: ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- include_tasks: arch.yml
  when: ansible_distribution == "Archlinux"

- name: Creates local node_modules directory
  file:
    path: "~/.node_modules/lib"
    state: directory
    recurse: yes

- name: Setup NPM prefix
  command: "/usr/bin/npm config set prefix ~/.node_modules"
  args:
    creates: "~/.npmrc"

- name: Install global modules
  npm: 
    name: "{ item }}"
    global: yes
  with_items:
    - prettier
    - eslint
    - create-react-app
    - firebase-tools
    - neovim
    - javascript-typescript-langserver
