---
- include_tasks: ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- include_tasks: arch.yml
  when: ansible_distribution == "Archlinux"

- name: Install global modules
  npm: 
    name: "{ item }}"
    global: yes
  with_items:
    - prettier
    - eslint
    - create-react-app
    - firebase-tools
    - neovim
    - javascript-typescript-langserver
