---
- name: Install extra dev tools
  pacman:
    name: "{{ item }}"
  become: yes
  with_items:
    - git
    - jq
    - curl
    - tmux
    - cloc
    - htop
    - ctags
    - pandoc
    - the_silver_searcher
    - dos2unix
    - jdk9-openjdk
    - jdk8-openjdk
    - heroku-cli
    - java-jce_ustrength
    - ngrok
