---
- name: Install extra dev tools
  apt:
    name: "{{ item }}"
  become: yes
  with_items:
    - git
    - jq
    - curl
    - tmux
    - cloc
    - direnv
    - rsync
    - htop
    - exuberant-ctags
    - cloud-utils
    - redis-tools
    - pandoc
    - silversearcher-ag
    - dos2unix
    - openjdk-8-jdk
    - openjdk-9-jdk

- name: Install extra compression utils
  apt:
    name: "{{ item }}"
  become: yes
  with_items:
    - p7zip-full
    - xz-utils
