---
- name: Install Docker repo key
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
  become: yes

- name: Install Docker repo
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu zesty stable"
  become: yes

- name: Install Docker
  apt:
    name: docker-ce
  become: yes
