---
- name: Install Docker repo key
  apt_key:
    keyserver: "p80.pool.sks-keyservers.net"
    id: "58118E89F3A912897C070ADBF76221572C52609D"
  become: yes

- name: Remove old Docker repo
  apt_repository:
    repo: "deb https://apt.dockerproject.org/repo ubuntu-{{ansible_distribution_release}} main"
    state: absent
  become: yes

- name: Install Docker repo
  apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} edge"
    state: absent
  become: yes

- name: Install Docker
  apt:
    name: docker-ce
  become: yes
