---
- name: Install base packages
  pacman:
    name: "{{ item }}"
  become: yes
  with_items:
    - base-devel
    - firefox
    - intel-ucode
    - autofs
    - isync
    - nfs-utils
    - aspell
    - aspell-es
    - aspell-en
    - mutt
    - weechat
    - lm_sensors
    - powertop
    - w3m
    - openssh
    - zsh
    - openvpn
    - ranger
    - networkmanager
    - intel-ucode
    - iw
    - wpa_supplicant
    - dialog
    - sudo
    - network-manager-applet
    - bc
    - imagemagick
    - libreoffice-fresh
    - cups
    - fwupd
    - avahi
    - rsync
    - nss-mdns
    - vdirsyncer

- name: Install packer deps
  pacman:
    name: "{{ item }}"
  become: yes
  with_items:
    - jshon

- name: Sync repos with packer
  command: packer -Syu

- name: Install base aur packages
  command: "packer --noedit --noconfirm -S {{ item }}"
  with_items:
    - urlview
    - direnv
    - networkmanager-dmenu-git
    - cloud-utils
    - mkpasswd
    - sbupdate-git
    - openvpn-update-systemd-resolved
    - packer

- name: Enable avahi daemon
  systemd:
    name: avahi-daemon
    enabled: yes
    state: started
  become: yes

- name: Enable cups daemon
  systemd:
    name: cups-browsed
    enabled: yes
    state: started
  become: yes
