---
- name: Install apt-transport-https
  apt:
    name: apt-transport-https
  become: yes

- name: Install base packages
  apt:
    name: "{{ item }}"
  become: yes
  with_items:
    - firefox
    - intel-microcode
    - autofs
    - nfs-common
    - urlview
    - isync
    - aspell-es
    - aspell-en
    - mutt
    - weechat
    - lm-sensors
    - powertop
    - w3m
    - openssh-server
    - zsh
    - openvpn
    - ranger
