---
- name: Install vim gtk3
  apt:
    name: vim-gtk3
  become: yes

- name: Create .vim directory
  file:
    path: "~/.vim"
    state: directory

- name: Install Plug
  get_url:
    url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    dest: "~/.vim/autoload/plug.vim"

