---
- name: Create bundle directory
  file:
    path: "~/.vim/bundle"
    state: directory
    recurse: yes

- name: Create autoload directory
  file:
    path: "~/.vim/autoload"
    state: directory
    recurse: yes

- name: Install Pathogen
  get_url:
    url: "https://raw.github.com/tpope/vim-pathogen/master/autoload/pathogen.vim"
    dest: "~/.vim/autoload/pathogen.vim"

- name: Install Vim plugins
  git:
    repo: "{{ item.repo }}"
    dest: "~/.vim/bundle/{{ item.name }}"
  with_items:
    - { repo: 'https://github.com/Shougo/neocomplete.vim', name: 'neocomplete.tool' }
    - { repo: 'https://github.com/scrooloose/nerdtree.git', name: 'nerdtree.tool' }
    - { repo: 'https://github.com/jeetsukumaran/vim-buffergator.git', name: 'buffergator.tool' }
    - { repo: 'https://github.com/tpope/vim-fugitive.git', name: 'fugitive.tool' }
    - { repo: 'https://github.com/fatih/vim-go.git', name: 'go.lang' }
    - { repo: 'https://github.com/pangloss/vim-javascript.git', name: 'javascript.lang' }
    - { repo: 'https://github.com/kien/ctrlp.vim.git', name: 'ctrlp.tool' }
    - { repo: 'https://github.com/Lokaltog/vim-easymotion.git', name: 'easymotion.tool' }
    - { repo: 'https://github.com/tpope/vim-git.git', name: 'git.lang' }
    - { repo: 'https://github.com/bronson/vim-trailing-whitespace.git', name: 'trailing-whitespace.tool' }
    - { repo: 'https://github.com/terryma/vim-multiple-cursors.git', name: 'multiple-cursors.tool' }
    - { repo: 'https://github.com/scrooloose/syntastic.git', name: 'syntastic.tool' }
    - { repo: 'https://github.com/tpope/vim-sensible.git', name: 'vim-sensible.config' }
    - { repo: 'https://github.com/majutsushi/tagbar.git', name: 'tagbar.tool' }
    - { repo: 'https://github.com/vim-scripts/ZoomWin.git', name: 'ZoomWin.tool' }
    - { repo: 'https://github.com/chriskempson/base16-vim.git', name: 'base16.color' }
    - { repo: 'https://github.com/SirVer/ultisnips.git', name: 'utilsnips.tool' }
    - { repo: 'https://github.com/hashivim/vim-terraform.git', name: 'terraform.lang' }
    - { repo: 'https://github.com/airblade/vim-gitgutter.git', name: 'gitgutter.tool' }
    - { repo: 'https://github.com/Chiel92/vim-autoformat.git', name: 'autoformat.tool' }
    - { repo: 'https://github.com/vim-airline/vim-airline.git', name: 'airline.tool' }

