#!/bin/sh

IN="eDP-1"
EXT="HDMI-1"

pkill polybar || true

polybar int &

if (xrandr | grep "$EXT disconnected"); then
  xrandr --output $EXT --off --output $IN --auto --primary
else
  xrandr --output $IN --auto --output $EXT --primary --mode 1920x1080 --panning 3840x2160+3840+0 --scale 2x2 --right-of $IN
  polybar ext &
  i3-msg "workspace 1, move workspace to output ${EXT}"
  i3-msg "workspace 2, move workspace to output ${EXT}"
  i3-msg "workspace 3, move workspace to output ${EXT}"
  i3-msg "workspace 10, move workspace to output ${IN}"
fi

feh --bg-scale ~/Pictures/wallpaper.png

#pkill compton
#compton --xrender-sync-fence &
