---
- name: Install NeoVim deps
  pacman:
    name: "{{ item }}"
  become: yes
  with_items:
    - python-neovim
    - python2-neovim
    - xsel

- name: Install NeoVim
  command: packer --noedit --noconfirm -S neovim-git

- name: Create .vim directory
  file:
    path: "~/.local/share/nvim/site/autoload"
    state: directory
    recurse: yes

- name: Install Plug
  get_url:
    url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    dest: "~/.local/share/nvim/site/autoload/plug.vim"

