---
- name: Install neovim PPA repo
  apt_repository:
    repo: ppa:neovim-ppa/unstable
  become: yes

- name: Install NeoVim deps
  apt:
    name: "{{ item }}"
  with_items:
    - python-dev
    - python-pip
    - python3-dev
    - python3-pip
  become: yes

- name: Install NeoVim
  apt:
    name: neovim
  become: yes
