---
- name: Install Ruby
  apt:
    name: "{{ item }}"
  become: yes
  with_items:
    - ruby
    - ruby-dev

- name: Install default Ruby Gems
  gem:
    name: "{{ item }}"
    user_install: yes
    state: latest
  with_items:
    - bundler
    - homesick
    - git-smart
    - ghost
    - travis

