---
- name: Install font awesome AUR
  command: packer --noedit --noconfirm -S ttf-font-awesome-4

- name: Install Fonts
  pacman:
    name: "{{ item }}"
  become: yes
  with_items:
    - ttf-hack
    - ttf-liberation
    - noto-fonts
    - noto-fonts-cjk
    - noto-fonts-emoji
    - noto-fonts-extra
