---
- name: Install Fonts
  apt:
    name: "{{ item }}"
  become: yes
  with_items:
    - fonts-font-awesome
    - fonts-hack-ttf
    - fonts-noto
    - fonts-noto-cjk
    - fonts-noto-mono
    - fonts-firacode
